### ISSUE TITLE
Can't use the app

### ISSUE THREAD

**Issue by matt911** [Blue9/AudioJack-GUI#26]
[log.txt](https://github.com/Blue9/AudioJack-GUI/files/942488/log.txt)
The window shows, but i can't click anything, neither press F1. I attached a log for the problem. Anyone can help me?

**Comment by Blue9** [comment]
This looks like an issue with Kivy. Try running the latest version of Kivy (1.9.2) by following the instructions [here](https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation). If that doesn't work, I suggest you open an issue on [their GitHub page](https://github.com/kivy/kivy/issues). In the meantime, you can use an older version of AudioJack-GUI [here](https://github.com/Blue9/AudioJack-GUI/tree/70ff3fc84b958beb71e1f61e5b322429ef281fde) which uses Tkinter instead of Kivy.
