### ISSUE TITLE
Closing of AudioJack-Web

### ISSUE THREAD

**Issue by kezz** [Blue9/AudioJack-GUI#8]
Are you closing the hosting of AudioJack Web because of costs or anything? If possible, I'd be more than willing to host AudioJack if you like?

**Comment by Blue9** [comment]
I am not closing AudioJack.io due to the costs. Currently, there is a disconnect between the web version and the offline version in terms of features and customization. For now, I plan to focus on the offline version exclusively to expand its feature set as much as possible. After that, I may reopen the web version with the added features.
